apiVersion: v1
kind: Service
metadata:
  name: alertsandnotifications
spec:
  selector:
    app: alertsandnotifications
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: 4004
    - protocol: TCP
      name: sockets
      port: 81
      targetPort: 5005
  type: ClusterIP
