apiVersion : apps/v1
kind: Deployment
metadata:
  name: c 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c
  template:
    metadata:
      labels:
        app: c 
    spec:
      containers:
        - name: c 
          image: pis6toregistrygroup.azurecr.io/c
          ports:
          - containerPort: 4004