apiVersion: apps/v1
kind: Deployment
metadata:
  name: climatedata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climatedata
  template:
    metadata:
      labels:
        app: climatedata
    spec:
      containers:
        - name: climatedata
          image: pis6toregistrygroup.azurecr.io/climatedata:10.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4003
            - containerPort: 5000
          env:
            - name: API_BASEURL
              value: "http://api-gateway:80"
      imagePullSecrets:
        - name: my-acr-secret
