apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoringstations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoringstations
  template:
    metadata:
      labels:
        app: monitoringstations
    spec:
      containers:
        - name: monitoringstations
          image: pis6toregistrygroup.azurecr.io/monitoringstations:2.0
          ports:
            - containerPort: 4002
      imagePullSecrets:
        - name: my-acr-secret
