apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoringstations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoringstations
  template:
    metadata:
      labels:
        app: monitoringstations
    spec:
      containers:
        - name: monitoringstations
          image: pis6toregistrygroup.azurecr.io/monitoringstations:5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
          env:
            - name: API_BASEURL
              value: "http://api-gateway:80"
      imagePullSecrets:
        - name: my-acr-secret
