apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: pis6toregistrygroup.azurecr.io/authentication:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
      imagePullSecrets:
        - name: my-acr-secret
