const ACTIVE_USER_STATUS = "Activo";
const BLOQUED_USER_STATUS = "Bloqueado";

const RESEARCHER_ROLE_NAME = "Investigador";
const ADMIN_ROLE_NAME = "Administrador";

const TEMP_SENSOR_NAME = "Temperatura";
const HUM_SENSOR_NAME = "Humedad";
const CO2_SENSOR_NAME = "CO2";
const ALLOWED_SENSORS = [TEMP_SENSOR_NAME, HUM_SENSOR_NAME, CO2_SENSOR_NAME];

const SENSOR_TYPES_DICTIONARY = {
  [TEMP_SENSOR_NAME]: { unit: "°C" },
  [HUM_SENSOR_NAME]: { unit: "%" },
  [CO2_SENSOR_NAME]: { unit: "ppm" },
};

const ACTIVE_STATUS_NAME = "Activo";
const INACTIVE_STATUS_NAME = "Inactivo";

//Alerts
const ERROR_TYPE_ALERT = "error" 
const WARN_TYPE_ALERT = "warn"
const SUCCESS_TYPE_ALERT = "success"
const INFO_TYPE_ALERT = "info"

module.exports = {
  ACTIVE_USER_STATUS,
  BLOQUED_USER_STATUS,
  RESEARCHER_ROLE_NAME,
  ADMIN_ROLE_NAME,
  TEMP_SENSOR_NAME,
  HUM_SENSOR_NAME,
  CO2_SENSOR_NAME,
  ALLOWED_SENSORS,
  SENSOR_TYPES_DICTIONARY,

  ACTIVE_STATUS_NAME,
  INACTIVE_STATUS_NAME,

  //Tipos de alertas
  ERROR_TYPE_ALERT,
  WARN_TYPE_ALERT,
  SUCCESS_TYPE_ALERT,
  INFO_TYPE_ALERT,
};
